// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9t1ISx_PAW9uQ92jeSGKYS9mRYkyYAU',
    appId: '1:990430511746:web:92593ed212ae5e4ebb2a9b',
    messagingSenderId: '990430511746',
    projectId: 'examen2-programovil-q3-2024',
    authDomain: 'examen2-programovil-q3-2024.firebaseapp.com',
    storageBucket: 'examen2-programovil-q3-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-9aYpL440NBHQfrvw8Ea7p_UouWXgQ4',
    appId: '1:990430511746:android:74b402418eca5ae8bb2a9b',
    messagingSenderId: '990430511746',
    projectId: 'examen2-programovil-q3-2024',
    storageBucket: 'examen2-programovil-q3-2024.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9t1ISx_PAW9uQ92jeSGKYS9mRYkyYAU',
    appId: '1:990430511746:web:da80753abee00324bb2a9b',
    messagingSenderId: '990430511746',
    projectId: 'examen2-programovil-q3-2024',
    authDomain: 'examen2-programovil-q3-2024.firebaseapp.com',
    storageBucket: 'examen2-programovil-q3-2024.appspot.com',
  );
}
